spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: void
    url: jdbc:postgresql://localhost:5432/product_service
  jpa:
    hibernate:
      ddl-auto: update